# Generated by Django 5.0.3 on 2024-04-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="キャラクター名称")),
            ],
            options={
                "db_table": "character",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="素材")),
            ],
            options={
                "db_table": "material",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="作品名")),
            ],
            options={
                "db_table": "work",
            },
        ),
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("create_date", models.DateField(verbose_name="完成日")),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.character",
                        verbose_name="キャラクターモチーフ",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(to="app.material", verbose_name="素材"),
                ),
            ],
            options={
                "db_table": "figure",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="app.work",
                verbose_name="作品名称",
            ),
        ),
    ]
